name: Artillery SocialMP Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  artillery:
    runs-on: ubuntu-latest

    container: artilleryio/artillery:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make reports directory
        run: mkdir reports

      - name: Execute max_performance_phase
        run: /home/node/artillery/bin/run run --output reports/mpreport.json --config config.yaml scenario_social.yaml

      - name: Generate HTML report max_performance_phase
        run: /home/node/artillery/bin/run report --output reports/report reports/mpreport.json

      - name: Execute reliability_test
        run: /home/node/artillery/bin/run run --output reports/relreport.json --config config.yaml -e reliability_test scenario_social.yaml

      - name: Generate HTML report reliability_test
        run: /home/node/artillery/bin/run report --output reports/report reports/relreport.json

      - name: Execute spike_test
        run: /home/node/artillery/bin/run run --output reports/spreport.json --config config.yaml -e spike_test scenario_social.yaml

      - name: Generate HTML report spike_test
        run: /home/node/artillery/bin/run report --output reports/report  reports/spreport.json

      - name: Archive test report
        uses: actions/upload-artifact@v2
        with:
          name: artillery-test-report
          path: reports/*